# https://esphome.io/components/binary_sensor/gpio.html
binary_sensor:
  - platform: gpio
    pin:
      number: ${button_pin}
      inverted: true
      # mode:
      #   input: true
      #   # https://esphome.io/components/binary_sensor/gpio#activating-internal-pullups
      #   pullup: true
    name: "${friendly_name} Button"
    id: atom_main_button
