esphome:
  name: ${node_name}
  # for more on friendly_name issues, see https://github.com/jzucker2/goober/blob/master/notes/ESPHOME.md
#  friendly_name: ${friendly_name}
  area: ${area}
  comment: ${comment}
  project:
    name: esphome.bluetooth-proxy
    version: "1.0"
