# https://esphome.io/components/debug.html
# Logger must be at least debug (default)
debug:
  update_interval: 5s

text_sensor:
  - platform: debug
    device:
      name: "Device Info"
      id: device_info
    reset_reason:
      name: "Reset Reason"
      id: reset_reason

sensor:
  - platform: debug
    free:
      name: "Heap Free"
      id: heap_free
    block:
      name: "Heap Max Block"
      id: heap_max_block
    loop_time:
      name: "Loop Time"
      id: loop_time
    cpu_frequency:
      name: "CPU Frequency"
      id: cpu_frequency
