sensor:
  - platform: mpu6886
    address: 0x68
    accel_x:
      name: "${node_name} MPU6886 Accel X"
    accel_y:
      name: "${node_name} MPU6886 Accel Y"
    accel_z:
      name: "${node_name} MPU6886 Accel z"
    gyro_x:
      name: "${node_name} MPU6886 Gyro X"
    gyro_y:
      name: "${node_name} MPU6886 Gyro Y"
    gyro_z:
      name: "${node_name} MPU6886 Gyro z"
    temperature:
      name: "${node_name} MPU6886 Temperature"
