# Used in cabinet lights
# https://esphome.io/components/light/esp32_rmt_led_strip
# https://esphome.io/components/light/
# intended for https://www.amazon.com/gp/product/B079ZW1265
- platform: esp32_rmt_led_strip
  rgb_order: GRB
  pin: "${light_data_pin}"
  # Changed in https://github.com/esphome/esphome/releases/tag/2025.7.0b1
  # rmt_channel: "${rmt_channel}"
  num_leds: "${num_leds}"
  is_rgbw: true
  restore_mode: RESTORE_DEFAULT_OFF
  chipset: SK6812
  id: "${led_strip_id}"
  icon: "${led_strip_icon}"
  name: "${friendly_name} ${led_strip_name} Light Strip"
  effects:
    - random:
    - flicker:
    - addressable_rainbow:
    - addressable_scan:
    - addressable_color_wipe:
    - addressable_twinkle:
    - addressable_random_twinkle:
    - addressable_fireworks:
    - addressable_flicker:
  on_turn_on:
    - logger.log: "Light Turned On!"
    - if:
        condition:
          # Same syntax for is_off
          switch.is_on: enable_white_light_hotfix_switch
        then:
          - logger.log: "The enable_white_light_hotfix_switch is true apply hotfix"
          - script.execute:
              id: turn_on_good_white_lights
          - logger.log: 'Done with enable white light hotfix'
        else:
          - logger.log: "Skipping hotfix because enable_white_light_hotfix_switch is false"
