esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino
    # notice the specific versions here
    # comes from https://community.home-assistant.io/t/got-the-lilygo-t-qt-esp32-s3-display-working/537328/7
    version: 2.0.3
    platform_version: 5.1.0
  variant: esp32s3

esphome:
  on_boot:
    - priority: 800
      then:
        - lambda: |-
            id(disp).enable();
            id(disp).transfer_byte(0x11);
            id(disp).disable();

# Enable logging
# https://hutscape.com/tutorials/hello-esphome-esp32s3
logger:
  level: VERBOSE
  baud_rate: 115200
  deassert_rts_dtr: true

i2c:
  - id: bus_a
    sda: GPIO38
    scl: GPIO39

spi:
  clk_pin: GPIO17
  mosi_pin: GPIO21
