# https://esphome.io/components/sensor/rotary_encoder.html
sensor:
  - platform: rotary_encoder
    name: "${friendly_name} Rotary Encoder"
    pin_a: D1
    pin_b: D2
    on_clockwise:
      then:
        - logger.log: "Turned Clockwise"
    on_anticlockwise:
      - logger.log: "Turned Anticlockwise"
