- platform: homeassistant
  name: "${friendly_name} Media Player Zone Volume"
  id: receiver_zone_volume
  entity_id: ${receiver_zone_media_player_entity}
  attribute: volume_level
  on_value:
    - logger.log:
        format: "The media_player volume sensor reports value %f"
        args: [ 'id(receiver_zone_volume).state' ]
    # always update volume
    - lambda: |-
        float volume = id(receiver_zone_volume).state;
        ESP_LOGD("hass_media_volume_callback", "got volume %f", volume);
        id(media_volume_value) = (volume * 100.0);
    # don't forget to update the rotary encoder
    - sensor.rotary_encoder.set_value:
        id: rotaryencoder
        value: !lambda 'return id(media_volume_value);'
    - if:
        condition:
          or:
            - display.is_displaying_page: VolumePage
        then:
          - component.update: my_lcd
