- platform: homeassistant
  name: "${friendly_name} Media Player Receiver Zone State"
  id: receiver_zone_state
  entity_id: ${receiver_zone_media_player_entity}
#  attribute: state
  on_value:
    - logger.log:
        format: "The receiver media_player state sensor reports value %s"
        args: [ 'x.c_str()' ]
    # always update volume
    - lambda: |-
        ESP_LOGD("hass_receiver_state_callback", "got state %s", x.c_str());
        id(media_zone_state).publish_state(x.c_str());
    - if:
        condition:
          or:
            - display.is_displaying_page: VolumePage
        then:
          - component.update: my_lcd
