# TODO: sync this with the `graybox/common/graybox_version_info.yaml` file
substitutions:
  box_version: "1.4.4"

esphome:
  project: !include {file: ../default_project.yaml, vars: {box_version: "${box_version}"}}

packages:
  dashboard_import: !include {file: ../default_dashboard_import.yaml, vars: {box_version: "${box_version}"}}
