# https://shop.m5stack.com/products/m5papers3-esp32s3-development-kit
# https://github.com/jesserockz/m5paper-esphome
# https://community.home-assistant.io/t/esp32-s3-compatibily-and-m5-paper-s3/876573/4
# https://github.com/esphome/feature-requests/issues/3052 (bmi270)
# https://github.com/patrick3399/esphome_components
# https://github.com/patrick3399/esphome_components/blob/main/m5stack-papers3.yaml
packages:
  esphome: !include m5papers3_esphome.yaml
  board: !include m5papers3_device.yaml
  wifi_base: !include ../templates/wifi_base.yaml
  goober_base: !include ../templates/base_goober.yaml
  psram: !include ../psram.yaml
  psram_debug: !include ../psram_debug.yaml
  shutdown: !include ../shutdown.yaml

globals:
  - id: system_initialized
    type: bool
    restore_value: no
    initial_value: 'false'

# https://esphome.io/components/switch/index.html
switch:
  # https://esphome.io/components/switch/template
  - platform: template
    name: "Enable Status Light Switch"
    id: enable_status_light_switch
    optimistic: true
    icon: "mdi:alarm-light"
    restore_mode: RESTORE_DEFAULT_ON

# https://esphome.io/components/script.html
script:
  - id: optionally_blink_status_light_script
    mode: single
    then:
      - if:
          condition:
            # Same syntax for is_off
            switch.is_on: enable_status_light_switch
          then:
            - logger.log: "The enable_status_light_switch is true so blink light"
            - light.turn_on: statled
            - delay: 1s
            - light.turn_off: statled
            - logger.log: 'Done with blink light'
          else:
            - logger.log: "Skipping blink light because enable_status_light_switch is false"

  - id: play_startup_sequence_script
    mode: single
    then:
      - logger.log: Play startup sequence tones
      - rtttl.play: 'siren:d=8,o=5,b=100:d,e,d,e,d,e,d,e'

button:
  # https://esphome.io/components/button/template.html
  - platform: template
    name: "Play Startup Sequence Button"
    id: play_startup_sequence_button
    icon: "mdi:music-circle-outline"
    disabled_by_default: true
    on_press:
      - logger.log: Play Startup Sequence Button Pressed
      - script.execute: play_startup_sequence_script

interval:
  - interval: 8s
    then:
      - script.execute: optionally_blink_status_light_script

external_components:
  - source: github://patrick3399/esphome_components
  # - source: github://n-serrette/esphome_sd_card   #If need SD Card Support

i2c:
  sda: GPIO41
  scl: GPIO42
  scan: true
  id: bus_internal
  frequency: 200kHz

# sd_mmc_card:  #If need SD Card Support
#   id: micro_sd
#   mode_1bit: true
#   clk_pin: GPIO7
#   cmd_pin: GPIO8
#   data0_pin: GPIO9
#   data3_pin: GPIO10

# sd_file_server:  #If need SD Card Support
#   id: file_server
#   url_prefix: file
#   root_path: "/"
#   enable_deletion: true
#   enable_download: true
#   enable_upload: true

touchscreen:
  platform: gt911
  id: my_touchscreen
  interrupt_pin: GPIO48
  display: ed047tc1_display
  transform:
    mirror_x: true
    mirror_y: true
    swap_xy: false
  on_release:
    - script.execute: lvgl_resume_script

light:
  - platform: monochromatic
    id: statled
    name: "Status LED"
    output: gpio_0
    restore_mode: ALWAYS_OFF
    internal: True
    disabled_by_default: True

output:
  - platform: ledc
    id: rtttl_pin
    pin: 21
  - platform: ledc
    id: gpio_0
    pin: 0
    inverted: True

# https://github.com/dhylands/upy-rtttl/blob/master/songs.py
rtttl:
  output: rtttl_pin
  id: rtttl_buzz
  gain: 60%

# text_sensor:
#   - platform: debug
#     device:
#       name: "Device Info"
#     reset_reason:
#       name: "Reset Reason"

sensor:
  # https://esphome.io/components/sensor/adc.html
  - platform: adc
    pin: GPIO3
    id: battery_voltage
    name: "Battery Voltage"
    update_interval: 30s
    attenuation: 12db
    filters:
      - multiply: 2.0

  # https://esphome.io/components/sensor/adc.html
  - platform: adc
    pin: GPIO5
    name: "USB DET"
    id: usb_detection
    update_interval: 30s
    attenuation: 12db
    filters:
      - multiply: 2.0

# - platform: sd_mmc_card  #If need SD Card Support
#   type: used_space
#   name: "SD card used space"
# - platform: sd_mmc_card
#   type: total_space
#   name: "SD card total space"

# text_sensor:
# - platform: sd_mmc_card  #If need SD Card Support
#   sd_card_type:
#     name: "SD card type"

binary_sensor:
  # https://esphome.io/components/binary_sensor/gpio.html
  - platform: gpio
    pin:
      number: 4
      inverted: True
    name: "Charge Status"
    id: charge_status_sensor
    device_class: battery_charging
    trigger_on_initial_state: true

time:
  - platform: pcf8563
    address: 0x51
    update_interval: 10min
  # https://esphome.io/components/time/homeassistant.html
  - id: !extend esptime
    on_time_sync:
      then:
        - pcf8563.write_time:

display:
  - platform: ed047tc1
    id: ed047tc1_display
    pwr_pin: GPIO45
    bst_en_pin: GPIO46
    xstl_pin: GPIO13
    xle_pin: GPIO15
    spv_pin: GPIO17
    ckv_pin: GPIO18
    pclk_pin: GPIO16
    d0_pin: GPIO6
    d1_pin: GPIO14
    d2_pin: GPIO7
    d3_pin: GPIO12
    d4_pin: GPIO9
    d5_pin: GPIO11
    d6_pin: GPIO8
    d7_pin: GPIO10
