- platform: touchscreen
  name: "${friendly_name} ${page_id} Zone Muted Button"
  page_id: "${page_id}"
  x_min: 90
  x_max: 150
  y_min: 170
  y_max: 230
  on_release:
    then:
      - lambda: |-
          ESP_LOGD("media_player_volume_mute", "touched zone muted button");
      - if:
          condition:
            light.is_on: backlight
          then:
            - script.execute:
                id: hass_zone_mute_set
                entity_id: "${receiver_zone_media_player_entity}"
            - lambda: |-
                ESP_LOGD("media_player_volume_mute", "after hass muted action");
