substitutions:
  node_name: example-remote-bluetooth-proxy
  friendly_name: Example Remote Bluetooth Proxy
  area: Example
  comment: "This is a decent iteration that is built from remote"
  box_config_file_name: example_remote_bluetooth_proxy

packages:
  wifi_base: !include common/templates/wifi_base.yaml
  bluetooth_proxy_template: !include common/bluetooth/white_idf_bluetooth_proxy_template.yaml
  graybox:
    url: https://github.com/jzucker2/graybox
    files: [
      graybox/common/s3_logger.yaml,
    ]
    ref: master
    refresh: 0d
