substitutions:
  node_name: examplegassensor
  friendly_name: Example Gas Sensor
  area: Example Room
  comment: "This senses gas as an example"
  box_config_file_name: example_gas_sensor

packages:
  graybox_complex:
    url: https://github.com/jzucker2/graybox
    files:
      - path: graybox/common/atom_idf_light.yaml
        vars:
          light_pin: 35
      - path: graybox/common/atom_idf_button.yaml
        vars:
          button_pin: 41
    ref: master
    refresh: 0d
  graybox:
    url: https://github.com/jzucker2/graybox
    files: [
      graybox/common/core/simple_esphome.yaml,
      graybox/common/s3_logger.yaml,
      graybox/common/boards/m5atoms3lite_idf_device.yaml,
      graybox/common/templates/wifi_base.yaml,
      graybox/common/templates/base_goober.yaml,
      graybox/common/s3_i2c.yaml,
      graybox/common/tvoc_sensor.yaml,
    ]
    ref: master
    refresh: 0d
