# https://www.reddit.com/r/Esphome/comments/1e2q8jj/m5_stack_airq_air_quality_sensor/
substitutions:
  node_name: exampleairqsensorv1
  friendly_name: Example AirQ Sensor V1
  area: Example Room
  comment: "This is the example for using an M5Stack AirQ sensor kit"
  box_config_file_name: example_air_q_sensor_v1
  display_location: "Example Room"
  sensor_interval: "60s"
  # Sensor calibration
  altitude_compensation: "16m"  # Local altitude for CO2 sensor

packages:
  graybox:
    url: https://github.com/jzucker2/graybox
    files: [
      graybox/common/default_logger.yaml,
      graybox/common/air_q_sensor/base_template.yaml,
      graybox/common/templates/graybox_project_details.yaml,
    ]
    ref: switching-over-more-examples
    refresh: 0d
