substitutions:
  node_name: example-local-bt-proxy
  friendly_name: Example Local Bluetooth Proxy
  area: Example
  comment: "This is a decent iteration that is built locally"
  box_config_file_name: example_local_bluetooth_proxy

packages:
  logging: !include common/s3_logger.yaml
  # logging: !include common/s3_debug_logger.yaml
  wifi_base: !include common/templates/wifi_base.yaml
  bluetooth_proxy_template: !include common/bluetooth/white_idf_bluetooth_proxy_template.yaml
