substitutions:
  node_name: example-remote-eth-bt-proxy
  friendly_name: Example Remote Ethernet Bluetooth Proxy
  area: Example
  comment: "This is a decent iteration that is built from remote for ethernet"
  box_config_file_name: example_remote_ethernet_bluetooth_proxy

packages:
  graybox:
    url: https://github.com/jzucker2/graybox
    files: [
      graybox/common/s3_logger.yaml,
      graybox/common/templates/ethernet_s3_base.yaml,
      graybox/common/bluetooth/white_idf_bluetooth_proxy_template.yaml
    ]
    ref: master
    refresh: 0d
