# https://github.com/patrickcollins12/esphome-fan-controller
sensor:
  # Read the Tacho PIN and show measured RPM as a sensor (only with 4-pin PWM fans!)
  # See instructions here: https://esphome.io/components/sensor/pulse_counter.html
  - platform: pulse_counter
    pin:
      number: "${rpm_pin}"   # Connect to any input PIN on the ESP
      mode: INPUT_PULLUP
    unit_of_measurement: 'RPM'
    id: fan_speed
    name: "${friendly_name} Fan Speed 1"
    accuracy_decimals: 0
    filters:
      - multiply: 0.5  # Depending on how many pulses the fan sends per round - should be 0.5 or 1 - try...
